---
# tasks register to satellite6 with or without puppet
#
- name: workaround as DNS is not working
  lineinfile: 
    dest: /etc/hosts
    line: "{{ sat6_ip }} {{ sat6_fqdn }} sat6"

- name: download file bootstrap.py from satellite6
  get_url:
    url: "http://{{ sat6_fqdn }}/pub/bootstrap.py"
    dest: /usr/local/sbin/bootstrap.py
  when: hostgroup != 'false'
  
- name: copy bootstrap script to /usr/local/sbin and make it executable
  file:
    path: /usr/local/sbin/bootstrap.py
    mode: 0755
    owner: root
    group: root
  when: hostgroup != 'false'

- name: register to satellite6 with puppet and fail if the host was already registered
  command: "/usr/local/sbin/bootstrap.py -l {{ admin_user}} -p {{ admin_pass }} -s {{ sat6_fqdn }} -o {{ org }} -L {{ loc }} -g {{ hostgroup }} -a {{ activationkey }}"
  when: hostgroup != 'false'

- name: install katello rpm if the value of withpuppet is not set
  command:  "/usr/bin/yum -y localinstall http://{{ sat6_fqdn }}/pub/katello-ca-consumer-latest.noarch.rpm"
  when: hostgroup == 'false'

- name: register to satellite6 just for content 
  command: "subscription-manager register --org={{ org }} --activationkey={{ activationkey }}"
  when: hostgroup == 'false'
  register: 'reg_return'

- name: install the katello-agent
  yum:
    name: katello-agent
    state: latest
  when: hostgroup == 'false' and reg_return|success
  notfiy:
    - Start katello-agent
    - Enable katello-agent
